[package]
name = "my_hello_world"
version = "0.1.0"
authors = ["Cesar Bretana Gonzalez <bretanac@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"